name: Build Python Exe

on:
  push:
    branches: [ master ]

jobs:
  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: swarmsync 
        artifact: swarmsync
        use-dependencies: true
        python_version: 3.10.6
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: swarmsync_${{ github.job }}
        path: dist
      
  ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: swarmsync
        artifact: swarmsync
        use-dependencies: true
        python_version: 3.10.6
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: swarmsync_${{ github.job }}
        path: dist
 
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: swarmsync
          artifact: swarmsync
          use-dependencies: true
          python_version: 3.10.6
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: swarmsync_${{ github.job }}
          path: dist
