name: Build Python Exe

on:
  push:
    tags:
      - '*'

jobs:
  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: swarmsync 
        artifact: swarmsync
        use-dependencies: true
        python_version: 3.10.6
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: swarmsync_${{ github.job }}
        path: dist
      
  ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: swarmsync
        artifact: swarmsync
        use-dependencies: true
        python_version: 3.10.6
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: swarmsync_${{ github.job }}
        path: dist
 
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: swarmsync
          artifact: swarmsync
          use-dependencies: true
          python_version: 3.10.6
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: swarmsync_${{ github.job }}
          path: dist

  release:
    needs: [ubuntu-22-04, ubuntu-20-04, windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
      - name: version
        run: | 
          chmod +x ./swarmsync_ubuntu-22-04/swarmsync
          VERSION=$(./swarmsync_ubuntu-22-04/swarmsync --version)
          echo "version=$VERSION" >> GITHUB_OUTPUT
          rm -rf swarmsync_ubuntu-22-04
        id: version
      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_OUTPUT
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.previousTag.outputs.previousTag }}
          writeToFile: false
          includeInvalidCommits: true
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: ${{ steps.changelog.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/download-artifact@v3
        with:
          name: swarmsync_ubuntu-22-04
          path: ./
      - name: debug
        run: |
          ls -lsatrh
          ls -R
      - name: upload ubuntu 22.04 artifact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: swarmsync_ubuntu-22-04
          asset_name: swarmsync_ubuntu-22-04
          asset_content_type: application/octet-stream
      - uses: actions/download-artifact@v3
        with:
          name: swarmsync_ubuntu-20-04
          path: ./
      - name: upload ubuntu 20.04 artifact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: swarmsync_ubuntu-20-04
          asset_name: swarmsync_ubuntu-20-04
          asset_content_type: application/octet-stream
      - uses: actions/download-artifact@v3
        with:
          name: swarmsync_windows
          path: ./
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: swarmsync_windows
          asset_name: swarmsync_windows
          asset_content_type: application/octet-stream
